[Module][Playbook] add zos_started_task sample playbook (#326)
* Update ansible-lint.yml

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update ansible-lint.yml

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update requirements.yml to include ansible.posix

Adding ansible.posix to resolve the ansible-lint issue

Error: couldn't resolve module/action 'ansible.posix.firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.
Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update ansible.cfg to include library path

Allows ansible-lint scan for custom zport library

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update ansible.cfg

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update .ansible-lint-ignore

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update ansible.cfg back out library

Backout library entry as it did not solve the ansible-lint issue.

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Adding zos_started_task samples

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update zos_started_task.yml

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Add missing dfsdf parameter

Signed-off-by: Sergio Saucedo <sergio.saucedo10@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Replace waitJob script with action query module

Signed-off-by: Sergio Saucedo <sergio.saucedo10@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* [Module][Playbook][1999]Playbook_for_zos_replace (#317)

* Add new text files

* Fix try

* Fix text

* Fix name

* Try check something

* Try check something

* Try check something

* To return to txt definition

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update zos_started_task.yml

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update requirements.yml

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Initial commit

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added ACC install folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* More fixes to the playbooks

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Creating 1.2.6 folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Updating the install flow

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* zhmc: Restructured sample playbooks

Details:

* Restructured the sample playbooks as follows:

  - Renamed them so that the resource they work on appears first in the file
    name, and then the action. This orders them in the directory listing in
    a more meaningful way.

  - Changed the variable that selects the inventory entry from 'host' to
    'hmc'.

  - Removed the 'cpc_name' variable from the vault file, since it is
    different for any HMC anyway, and it is easier to understand if it
    does not appear defined by magic. The CPC is now defined in each
    playbook with the 'cpc' variable and thus can be overridden from
    the command line with '-e cpc=mycpc'.

  - Simplified the variable names that specify resource names to remove
    '_name' for easier use with the '-e' option.

  - Added 'gather_facts: no' to the playbooks.

  - Added a zhmc log file 'zhmc.log' to the playbooks.

* Simplifications in the inventory and vault files:

  - Added the 'verify' variable to the example vault file.

  - Removed 'ansible_connection: local' from the example inventory file
    since it is not needed, when the tasks specify 'delegate_to: local'.

  - Improved the documentation in the example inventory  and vault files.

* Major improvements in the z_systems_administration/zhmc/README.md file
  that documents how to use the sample playbooks.

Signed-off-by: Andreas Maier <maiera@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Updating the README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Updating the README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added new playbooks

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes to address installation issues

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* ACC install scripts fixed

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixes in other use cases

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Major fixes in deploy playbooks

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Updated README.md file

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Updated README: added info about community.general

Signed-off-by: Dibya <Dibya.Raj@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added new line at the end of all 4 files(01-preparation.yaml, 02-create-cluster-control.yaml,04-destroy.yaml,approve_worker.yaml)

Signed-off-by: Dibya Raj <dibya.raj@ibm.com>
Signed-off-by: Dibya <Dibya.Raj@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header in installer

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed header again

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Made changes to allow deployment of storage/infra nodes

Signed-off-by: Paul Stefos <Paul.Stefos@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Cleaned up readme

Signed-off-by: Paul Stefos <Paul.Stefos@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update security groups to include additional security groups if specified

Update security groups to include additional security groups if specified using add_secgroups variable

Signed-off-by: Paul Stefos <Paul.Stefos@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Starting contribution for 12-12-25

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added the modified README.md files

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Modified READMEs and a figure

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed the acc_install_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Renamed the files

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Preparing other_usecases_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying other_usecases_ansible

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying ssa_deploy_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying appliance_deploy_default_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying appliance_deploy_default_mfa_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying appliance_deploy_standalone_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Copying appliance_deploy_standalone_mfa_ansible folder

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Applying requested changes

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Starting changes for 13.02.2026

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Change playbook for new modifications to C4Z api.

Signed-off-by: Thomas.Hsu <thomas.hsu@ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes for ACC 1.2.12

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixed the credentials figure in README.md

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Resolving PR comments

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update Copyright year

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update zos_started_task.yml

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update sample.jcl

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Update zos_started_task.yml

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Adding in samples for Software Update additions.

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Adding comments and an extra playbook pair.

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Nits from Kurt.

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Forgot to add comments about using environment variables in out variable files.

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Resolving PR review comments

Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Starting changes for 02.04.2026

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes for default mfa samples

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes for standalone samples

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes for standalone mfa samples

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added changes for other usecases

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added ACC install scripts

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added SSA install scripts

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added ACC install image

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added information about standalone mode

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Added input and fixes

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Bug fixes for standalone

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Fixes as requested

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

* Missed one fix

Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>

---------

Signed-off-by: ddimatos <dimatos@gmail.com>
Signed-off-by: surendrababuravella <39149274+surendrababuravella@users.noreply.github.com>
Signed-off-by: Sergio Saucedo <sergio.saucedo10@gmail.com>
Signed-off-by: M. Usman K. Khan <mkhan@de.ibm.com>
Signed-off-by: Andreas Maier <maiera@de.ibm.com>
Signed-off-by: Dibya <Dibya.Raj@ibm.com>
Signed-off-by: Dibya Raj <dibya.raj@ibm.com>
Signed-off-by: Paul Stefos <Paul.Stefos@ibm.com>
Signed-off-by: Thomas.Hsu <thomas.hsu@ibm.com>
Co-authored-by: Fernando Flores <fernandofloresdev@gmail.com>
Co-authored-by: Demetri <dimatos@gmail.com>
Co-authored-by: Sergio Saucedo <sergio.saucedo10@gmail.com>
Co-authored-by: André Marcel Gutiérrez Benítez <68956970+AndreMarcel99@users.noreply.github.com>
Co-authored-by: M. Usman K. Khan <mkhan@de.ibm.com>
Co-authored-by: Andreas Maier <maiera@de.ibm.com>
Co-authored-by: Dibya <Dibya.Raj@ibm.com>
Co-authored-by: Paul Stefos <Paul.Stefos@ibm.com>
Co-authored-by: thomas.hsu <thomas.hsu@ibm.com>
Co-authored-by: Aaron Michael Kippins <amkippin@us.ibm.com>